name: app
description: "Flutter application boilerplate with Flutter 3.19"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.1
  # device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  # intl: ^0.19.0
  dio: ^5.4.1
  share_plus: ^7.2.2
  url_launcher: ^6.1.8
  flutter_jailbreak_detection: ^1.10.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  permission_handler: ^10.2.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.2
  pin_code_fields: ^8.0.1
  otp_autofill: ^3.0.2
  local_auth: ^2.1.7
  crypto: ^3.0.3
  flutter_typeahead: ^5.2.0
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  mobile_scanner: ^4.0.0
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.3
  introduction_screen: ^3.1.6
  device_info_plus: ^11.1.1
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  camera: ^0.11.0+2
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  contacts_service: ^0.6.3
  fl_chart: ^0.69.2
  grouped_list: ^6.0.0
  flutter_contacts: ^1.1.9+2
  # intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/i18n/
    - assets/translations/
    - assets/icons/
    - assets/icons/settings/



  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_Black.ttf
        - asset: assets/fonts/inter/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_Light.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_Bold.ttf
          weight: 600

    - family: exo2
      fonts:
        - asset: assets/fonts/exo2/Exo2-Black.ttf
        - asset: assets/fonts/exo2/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/exo2/Exo2-Light.ttf
          weight: 600
        - asset: assets/fonts/exo2/Exo2-Bold.ttf
          weight: 600

    - family: spacegrotsek
      fonts:
        - asset: assets/fonts/spacegrotsek/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/spacegrotsek/SpaceGrotesk-Light.ttf
          weight: 500
        - asset: assets/fonts/spacegrotsek/SpaceGrotesk-Medium.ttf
          weight: 600
        - asset: assets/fonts/spacegrotsek/SpaceGrotesk-Regular.ttf
          weight: 600

    - family: jost
      fonts:
        - asset: assets/fonts/jost/Jost-Bold.ttf
        - asset: assets/fonts/jost/Jost-Light.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 600
        - asset: assets/fonts/jost/Jost-Regular.ttf
          weight: 600      